App: # APP基础设置项
  RunMode: debug
  AttachmentIncomeRate: 0.8
  MaxCommentCount: 1000
  DefaultContextTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
Cache:
  KeyPoolSize: 256            # 键的池大小， 设置范围[128, ++], 默认256
  CientSideCacheExpire: 60    # 客户端缓存过期时间 默认60s
  UnreadMsgExpire: 60         # 未读消息过期时间，单位秒， 默认60s
  UserTweetsExpire: 60        # 获取用户推文列表过期时间，单位秒， 默认60s
EventManager: # 事件管理器的配置参数
  MinWorker: 10               # 最小后台工作者, 设置范围[5, ++], 默认10
  MaxEventBuf: 100            # 最大log缓存条数, 设置范围[10, ++], 默认100
  MaxTempEventBuf: 100        # 最大log缓存条数, 设置范围[10, ++], 默认100
  MaxTickCount: 60            # 最大的循环周期, 设置范围[60, ++], 默认60
  TickWaitTime: 1             # 一个周期的等待时间，单位：秒 默认1s
Features:
  Default: []
WebServer: # Web服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8008
  ReadTimeout: 60
  WriteTimeout: 60
AdminServer: # Admin后台运维服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8014
  ReadTimeout: 60
  WriteTimeout: 60
SpaceXServer: # SpaceX服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8012
  ReadTimeout: 60
  WriteTimeout: 60
BotServer: # Bot服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8016
  ReadTimeout: 60
  WriteTimeout: 60
LocalossServer: # Localoss服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8018
  ReadTimeout: 60
  WriteTimeout: 60
PprofServer: # Pprof服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 6060
  ReadTimeout: 60
  WriteTimeout: 60
FrontendWebServer: # Web前端静态资源服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8006
  ReadTimeout: 60
  WriteTimeout: 60
DocsServer: # 开发文档服务
  RunMode: debug
  HttpIp: 0.0.0.0
  HttpPort: 8011
  ReadTimeout: 60
  WriteTimeout: 60
MobileServer: # 移动端grpc api服务
  Host: 0.0.0.0
  Port: 8020
SmsJuhe:
  Gateway: https://v.juhe.cn/sms/send
  Key:
  TplID:
  TplVal: "#code#=%s&#m#=%d"
Alipay: 
  AppID: "paopao-ce-app-id"
  InProduction: True
  PrivateKey: "MIICXAIBAAKBgQCzXV/spaX9+eOjM5f12W6eDTtszU9f9rgpXG4EQwzZI3WM5+Fe+9Bn6NQQILfF1o3Z+3BEzHMMcYwxrQw/toq2o6JPchbUK7eArKc6pl/GV3uIefZdKncz5bZvCFMgiJrpy75lYKhJgotQFEfQd+ks2t0gtC007uOjmY9QDB2EVQIDAQABAoGAMruhi0UbW2gYHCxWuiJDKI9jlJXJ8sHNO126fJgehTiDYlSgKYaeXxW7DcjDUkEqpFJ7YepWTFm9prtksIzIVQFNNjstI6cvowVF2t+lWf7mIB4w0ugarVd+SXssQK830Og3kjtZ84a3BbC6uf3a/qcgoIO8Sj1VnzOJ8fEYl+0CQQDeG6JhauGDOC8oCTwbFs9QPpjwGnp7UkYAJNg7jn4uBSVeg4lwb5uj9TshLSp49geNkPcWeCythuiz1jvoTqEjAkEAzrwIBxUPT1WmcDUXAkVPaQNADDbhMZLdw5nHZEUVwmO3o1FkJky4MLjLjT977400mhsnsQCy4sAWUZs6aEyoJwJARK3U2zy6eOHhqwaYAGRgPJbuoaf+Ya3CGX9LIbdhCwfqUzxnPk40mVFWNF8L+BVTppHB5b/JSOsjf6BqK95McwJBAL+kvUhbdHrV6lmgTXkUaV3u3mO0SCPdgui9WIKSLG6sY+LpI48BlcnMtR12WVyjKL0nKS9Dd5EOAmKaJJXlYgcCQGWbWCn9KUDUqpm4o3wr5nwXzlS74XYZo65UAM7TSzHRpcovfv5uiQ0VRLImWeiSXKK2aTOBGn5eKbevRTxN07k="
  RootCertFile: "custom/alipay/RootCert.crt"
  PublicCertFile: "custom/alipay/CertPublicKey_RSA2.crt"
  AppPublicCertFile: "custom/alipay/AppCertPublicKey.crt" 
CacheIndex:
  MaxUpdateQPS: 100             # 最大添加/删除/更新Post的QPS, 设置范围[10, 10000], 默认100
SimpleCacheIndex: # 缓存泡泡广场消息流
  MaxIndexSize: 200             # 最大缓存条数
  CheckTickDuration: 60         # 循环自检查每多少秒一次
  ExpireTickDuration: 300       # 每多少秒后强制过期缓存, 设置为0禁止强制使缓存过期
BigCacheIndex: # 使用BigCache缓存泡泡广场消息流
  MaxIndexPage: 1024            # 最大缓存页数，必须是2^n, 代表最大同时缓存多少页数据
  HardMaxCacheSize: 256         # 最大缓存大小(MB)，0表示无限制
  Verbose: False                # 是否打印cache操作的log
  ExpireInSecond: 300           # 多少秒(>0)后强制过期缓存
RedisCacheIndex: # 使用Redis缓存泡泡广场消息流
  Verbose: False                # 是否打印cache操作的log
  ExpireInSecond: 300           # 多少秒(>0)后强制过期缓存
Pyroscope: # Pyroscope配置
  AppName: "paopao-ce"                # application name
  Endpoint: "http://localhost:4040"   # Pyroscope server address
  AuthToken:                          # Pyroscope authentication token
  Logger:  none                       # Pyroscope logger (standard | logrus | none)
Sentry: # Sentry配置
  Dsn: "http://4ea0af5cd88d4512b7e52070506c80ec@localhost:9000/2"
  Debug: True
  AttachStacktrace: True
  TracesSampleRate: 1.0
  AttachLogrus: True  # logrus是否附加到Sentry
  AttachGin: True     # gin是否附加到Sentry
Logger: # 日志通用配置
  Level: debug # 日志级别 panic|fatal|error|warn|info|debug|trace
LoggerFile: # 使用File写日志
  SavePath: custom/data/paopao-ce/logs
  FileName: app
  FileExt: .log
LoggerZinc: # 使用Zinc写日志
  Host: zinc:4080
  Index: paopao-log
  User: admin
  Password: admin
  Secure: False
LoggerMeili: # 使用Meili写日志
  Host: meili:7700
  Index: paopao-log
  ApiKey: paopao-meilisearch
  Secure: False
  MinWorker: 5               # 最小后台工作者, 设置范围[5, 100], 默认5
  MaxLogBuffer: 100          # 最大log缓存条数, 设置范围[10, 10000], 默认100
LoggerOpenObserve: # 使用OpenObserve写日志
  Host: 127.0.0.1:5080
  Organization: paopao-ce
  Stream: default
  User: root@paopao.info
  Password: tiFEI8UeJWuYA7kN
  Secure: False
  MinWorker: 5               # 最小后台工作者, 设置范围[5, 100], 默认5
  MaxLogBuffer: 100          # 最大log缓存条数, 设置范围[10, 10000], 默认100
JWT: # 鉴权加密
  Secret: 18a6413dc4fe394c66345ebe501b2f26
  Issuer: paopao-api
  Expire: 86400
TweetSearch: # 推文关键字搜索相关配置
  MaxUpdateQPS: 100            # 最大添加/删除/更新Post的QPS，设置范围[10, 10000], 默认100
  MinWorker: 10                # 最小后台更新工作者, 设置范围[5, 1000], 默认10
Zinc: # Zinc搜索配置
  Host: zinc:4080
  Index: paopao-data
  User: admin
  Password: admin
  Secure: False
Meili: # Meili搜索配置
  Host: meili:7700
  Index: paopao-data
  ApiKey: paopao-meilisearch
  Secure: False
ObjectStorage: # 对象存储通用配置
  RetainInDays: 2   # 临时对象过期时间多少天
  TempDir: tmp      # 临时对象存放目录名
AliOSS: # 阿里云OSS存储配置
  Endpoint: 
  AccessKeyID: 
  AccessKeySecret: 
  Bucket: 
  Domain: 
COS: # 腾讯云COS存储配置
  SecretID: 
  SecretKey: 
  Region: ap-shanghai
  Bucket: demo-1888888888
  Domain: 
HuaweiOBS: # 华为云OBS存储配置
  AccessKey: 
  SecretKey: 
  Endpoint: 
  Bucket: paopao
  Domain: 
MinIO: # MinIO 存储配置
  AccessKey: Q3AM3UQ867SPQQA43P2F
  SecretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  Secure: False
  Endpoint: minio:9000
  Bucket: paopao
  Domain: 127.0.0.1:9000
S3: # Amazon S3 存储配置
  AccessKey: "YOUR-ACCESSKEYID"
  SecretKey: "YOUR-SECRETACCESSKEY"
  Secure: True
  Endpoint: s3.amazonaws.com
  Bucket: paopao
  Domain: 
LocalOSS: # 本地文件OSS存储配置
  SavePath: custom/data/paopao-ce/oss
  Secure: False
  Bucket: paopao
  Domain: 127.0.0.1:8008
Database: # Database通用配置
  LogLevel: error   # 日志级别 silent|error|warn|info
  TablePrefix: p_   # 表名前缀
MySQL: # MySQL数据库
  Username: paopao
  Password: paopao
  Host: db:3306
  DBName: paopao
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Postgres: # PostgreSQL数据库
  User: paopao
  Password: paopao
  DBName: paopao
  Schema: public
  Host: localhost
  Port: 5432
  SSLMode: disable
  ApplicationName:
Sqlite3: # Sqlite3数据库
  Path: custom/data/sqlite3/paopao-ce.db
Redis:
  InitAddress:
  - redis:6379
  Username:
  Password:
  SelectDB:
  ConnWriteTimeout: 60   # 连接写超时时间 多少秒 默认 60秒
  